version: '3'
services:
  producer:
    env_file:
      - .env
    depends_on:
      - redis
    image: long2ice/mysql2ch
    command: mysql2ch produce
  consumer.test:
    env_file:
      - .env
    depends_on:
      - redis
      - producer
    image: long2ice/mysql2ch
    command: mysql2ch consume --schema test
  ui:
    env_file:
      - .env
    depends_on:
      - redis
      - producer
      - consumer
    ports:
    - 5000:5000
    image: long2ice/mysql2ch
    command: mysql2ch ui
  redis:
    hostname: redis
    image: redis:latest
    volumes:
      - redis:/data
volumes:
  redis: