[tool.poetry]
name = "mysql2ch"
version = "0.4.5"
description = "Sync data from MySQL to ClickHouse, support full and increment ETL."
authors = ["long2ice <long2ice@gmail.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/long2ice/mysql2ch"
repository = "git@github.com:long2ice/mysql2ch.git"
documentation = "https://github.com/long2ice/mysql2ch"
keywords = ["MySQL", "ClickHouse", "Sync"]
packages = [
    { include = "mysql2ch" }
]
include = ["CHANGELOG.md", "LICENSE", "README.rst"]

[tool.poetry.dependencies]
python = "^3.6"
mysql-replication = "*"
clickhouse-driver = "*"
redis = "*"
mysqlclient = "*"
sentry-sdk = "*"
kafka-python = "*"
python-dateutil = "*"
pydantic = "*"
sqlparse = "*"

[tool.poetry.dev-dependencies]
taskipy = "*"
pytest = "*"
asynctest = "*"
flake8 = "*"
isort = "*"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
aerich = "mysql2ch = mysql2ch.cli:cli"