name: ci
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Add hosts
        run: sudo echo "$(ip addr show eth0 | grep -Po 'inet \K[\d.]+') redis mysql postgres clickhouse" | sudo tee -a /etc/hosts
      - uses: actions/checkout@v2
      - name: Run docker-compose
        run: docker-compose -f tests/docker-compose.yml up -d
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - uses: dschep/install-poetry-action@v1.3
      - name: ci
        run: make ci
