name: pypi
on:
  release:
    types:
      - created
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dschep/install-poetry-action@v1.3
      - name: Pypi Publish
        run: |
          make build
          make publish